# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OqybfAgkmUZJUQQOpQiT-pBIX4ILQkHL
"""

# First was some intro to the python language
# This also is a part of intro of version controlling via github
# Opening and using a file in python
with open("new.text","w+") as work:
  print(work.read())
  work.write("The quick brown fox jumps over the lazy dog.")
  work.close()

# I want to skim through all these and complete the course by 27-SEP-24 ("9 + 22 hours")
  # Again asked to make a calc 🫠

  # INITIAL SETUP
print("Welcome to the calculator")
fir_num = int(input("Please input the first Number\n"))
sec_num = int(input("Please input the Second Number\n"))

def ask_op():
  operator = input("Which operation would you like to do? \n +,-,/ or * \n")
  return operator

operator = str(ask_op())
result = ""

# main
def calc(op,num1,num2):
  num1 = int(num1)
  num2 = int(num2)
  if op == '+':
    result = num1+num2
  elif op == '-':
    result = num1-num2
  elif op == "/":
    result = num1/num2
  elif op == "*":
    result = num1*num2
  else:
    print("Please select a available operator\n")
    op = ask_op()
  return result
res = calc(op=operator,num1=fir_num,num2=sec_num)
print("The result is:"+str(res))

# LOOPING
def loop(res):
  ques = str(input("You want to proceed y/n: \n")).lower()
  while ques == "y":
    if ques == "y":
      num3 = int(input("Please input the next number.\n"))
      op = ask_op()
      res = calc(op=op,num1=int(res),num2=int(num3))
      print(res)
      print("The result is:"+ str(res))
    else:
      None
    ques = str(input("You want to proceed y/n: \n")).lower()
loop(res=res)

# NEED TO BE ON THE SAME BLOCK FOR IT TO WORK:
# main
print("Welcome to the calculator")
fir_num = int(input("Please input the first Number\n"))
sec_num = int(input("Please input the Second Number\n"))

def ask_op():
  operator = input("Which operation would you like to do? \n +,-,/ or * \n")
  return operator

operator = str(ask_op())
result = ""
def calc(op,num1,num2):
  num1 = int(num1)
  num2 = int(num2)
  if op == '+':
    result = num1+num2
  elif op == '-':
    result = num1-num2
  elif op == "/":
    result = num1/num2
  elif op == "*":
    result = num1*num2
  else:
    print("Please select a available operator\n")
    op = ask_op()
  return result
res = calc(op=operator,num1=fir_num,num2=sec_num)
print("The result is:"+str(res))

# LOOPING
def loop(res):
  ques = str(input("You want to proceed y/n: \n")).lower()
  while ques == "y":
    if ques == "y":
      num3 = int(input("Please input the next number.\n"))
      op = ask_op()
      res = calc(op=op,num1=int(res),num2=int(num3))
      print(res)
      print("The result is:"+ str(res))
    else:
      None
    ques = str(input("You want to proceed y/n: \n")).lower()
loop(res=res)
